version: '3.1'
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: blog_development
            POSTGRES_PASSWORD: blog_development
        volumes:
            - /tmp/db:/var/lib/postgresql/data
    web:
        build: .
        command: bundle exec rails server -p 3000 -b 0.0.0.0
        environment:
            RAILS_ENV: development
            DB_HOST: db
            DB_USERNAME: blog_development
            DB_PASSWORD: blog_development
        volumes:
            - .:/application:cached
        ports:
            - 3000:3000
        depends_on:
            - db